### ISSUE TITLE
No track found.

### ISSUE THREAD

**Issue by Yazurka** [kjbrum/spotifyCurrentlyPlaying.js#7]
Hi!

Im trying out the functionality to have a widget in my webpage with the song currently playing in spotify

on this line (120) var tracks = data.recenttracks.track;
(in the non-minimized version) i always get no result in the tracks array and this lable is shown on the website: "No track found."

I have made myself a last.fm user 
I have a api key
I have connected spotify to last.fm trough their web page
(I downloaded spotifyCurrentlyPlaying.js and added it to my project for debugging)
I did a init like this:
```
        SpotifyCurrentlyPlaying({
    selector: '#spotify-widget',
    username: 'myUsername',
    api_key: 'xxxxxxxxxxxxx',
    width: '100%',
    height: '370'
});
```
I added a div in my html: ```<div id="spotify-widget"></div>```
Im using Google Chrome version: #62.0.3202.89
And im playing a song on spotify.

I can't see what im doing wrong here.

Best regards Marius

**Comment by kjbrum** [comment]
Unfortunately, I don't think it will work anymore. You can take a look at #6 for the reasoning.

If you happen to figure it out, please create a pull request or let me know.

**Comment by Yazurka** [comment]
Oh, i see.
Thank you for your fast reply.

i've been working with the Spotify api for some weeks now and i see that it makes sense.
In my current solution to resolve what song is playing i have authorized my requests to spotify according to their documentation under Authorization Code Flow :https://developer.spotify.com/web-api/authorization-guide/ and that gets the job done. Nevertheless i would like to see them implement webhooks or pushmessage of some sort.

Thanks again 

Best regards Marius
